### ISSUE TITLE
Use of uninitialized value in subroutine with Circos tutorial

### ISSUE THREAD

**Issue by nvannier-mpipz** [galaxyproject/training-material#1723] opened 2020-01-22 10:11 UTC
Hi, 
I am new to Galaxy and Circos and tried running the visualization with Circos tutorial but ran into this error: 

Job ID | 26548657 (bbd44e69cb8906b58347e7c789706954)
-- | --
Tool ID | toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy1
Tool Version | 0.69.8+galaxy1
Job PID or DRM id | 21157219
Job Tool Version | circos \| v 0.69-8 \| 15 Jun 2019 \| Perl 5.026002

**stderr**
`Use of uninitialized value in subroutine entry at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3ceefac652df6e22f19dc71b30e6d4f2b0227c86bc0ffdf6ce30cc1d9a68e4a6/bin/../lib/Circos/Configuration.pm line 781.`

`Can't call method "colorExact" on an undefined value at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3ceefac652df6e22f19dc71b30e6d4f2b0227c86bc0ffdf6ce30cc1d9a68e4a6/bin/../lib/Circos/Colors.pm line 348, <F> line 24.`

Any idea where this error could come from ?

**Comment by hexylena** [comment] 2020-01-22 10:26
Hi @nvannier-mpipz which server are you running circos on? Try the latest version of circos, +galaxy3, which should have fixed dependencies.

**Comment by nvannier-mpipz** [comment] 2020-01-22 10:55
Hi @hexylena, 

I am running Circos on usegalaxy.org. 

On which server can i find these latest version ? 

Thanks for the help

**Comment by hexylena** [comment] 2020-01-22 10:56
Hi @nvannier-mpipz you can try it on usegalaxy.eu for now, and we will see about getting it working on .org  :)  (@natefoo, we had the same error, we had some issues with the environment created, some of the singularity images work tho? dunno)

**Comment by nvannier-mpipz** [comment] 2020-01-22 12:26
Hi @hexylena, 

It works perfectly on usegalaxy.eu, thanks !

**Comment by hexylena** [comment] 2020-01-22 13:39
Awesome! I'm sure .org will have that sorted out soon :)

**Comment by natefoo** [comment] 2020-01-22 16:44
@hexylena you're using singularity for this? Or did you get the Conda env working?

**Comment by bgruening** [comment] 2020-01-23 13:57
@natefoo we are using conda for the moment, waiting to finish all Singularity containers.

**Comment by natefoo** [comment] 2020-01-23 22:31
Sounds like we just need to update Circos then?

**Comment by jennaj** [comment] 2021-05-12 20:47
Update: Updated at UseGalaxy.org and works great

**Comment by cat-bro** [comment] 2021-05-25 08:00
We're seeing the same error for circos versions 0.69.8+galaxy7, 0.69.8+galaxy4 (and probably other versions) on Galaxy Australia.  We installed it in November and it seems to have been OK until April, and has been breaking with `Can't call method "colorExact" on an undefined value` ever since.  Probably some underlying lib.*.so is blank but I've no idea where to start looking for this.

**Comment by hexylena** [comment] 2021-05-25 08:11
@cat-bro can you share the history?

colorExact is a function I defined, so it's definitely on the galaxy end. This is usually caused by bad input data (e.g. some empty values) or bad configuration which causes undefineds (certain math operations)

**Comment by cat-bro** [comment] 2021-05-25 23:24
thanks @hexylena: https://usegalaxy.org.au/u/cat-bro/h/testhistory-1.  This is from the tool tests but it has been reported by regular users as well.  I've run the tests on .eu and .org.  No errors on .eu but .org has the same error (https://usegalaxy.org/u/cat-bro/h/testhistory)

**Comment by hexylena** [comment] 2021-05-26 13:30
I'm thinking you're right about the dependencies having issues, I misread the failing function initially. I've attached the conda env's details if it helps.

I've compared the jobs and what should be running locally and as far as I can tell, there's really nothing that would trigger this other than dependency issues.

<details>
<summary>EU's Conda Env Details</summary>

```
(mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368) root@sn06:/home/centos$ conda env export
name: mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - bcbiogff=0.6.4=py_1
  - biopython=1.70=py27_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2019.11.28=py27h8c360ce_1
  - circos=0.69.8=0
  - circos-tools=0.23=2
  - clustalw=2.1=hc9558a2_5
  - curl=7.69.1=h33f0ec9_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.1=he06d7ca_0
  - fribidi=1.0.9=h516909a_0
  - gawk=5.1.0=h516909a_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.64.2=h6f030ca_0
  - graphite2=1.3.13=he1b5a44_1001
  - graphviz=2.42.3=h0511662_0
  - grep=3.4=h516909a_0
  - harfbuzz=2.4.0=h9f30f68_3
  - icu=64.2=he1b5a44_1
  - jpeg=9c=h14c3975_1001
  - krb5=1.17.1=h2fd8d38_0
  - ld_impl_linux-64=2.34=h53a641e_0
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcurl=7.69.1=hf7181ac_0
  - libdb=6.1.26=he1b5a44_2002
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgd=2.2.5=h307a58e_1007
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=16_openblas
  - libopenblas=0.3.9=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_1
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hee79883_0
  - libxslt=1.1.33=h31b3aaa_0
  - llvm-openmp=10.0.0=hc9558a2_0
  - lz4-c=1.9.2=he1b5a44_0
  - ncurses=6.1=hf484d3e_1002
  - numpy=1.16.5=py27h95a1406_0
  - openssl=1.1.1g=h516909a_0
  - paml=4.9=h516909a_5
  - pango=1.42.4=h7062337_4
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - perl-aceperl=1.92=pl526_2
  - perl-algorithm-diff=1.1903=pl526_2
  - perl-algorithm-munkres=0.08=pl526_1
  - perl-apache-test=1.40=pl526_1
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-appconfig=1.71=pl526_1
  - perl-array-compare=3.0.1=pl526_1
  - perl-autoloader=5.74=pl526_2
  - perl-base=2.23=pl526_1
  - perl-bio-asn1-entrezgene=1.73=pl526_1
  - perl-bio-coordinate=1.007001=pl526_1
  - perl-bio-featureio=1.6.905=pl526_2
  - perl-bio-phylo=0.58=pl526_2
  - perl-bio-samtools=1.43=pl526h1341992_1
  - perl-bio-tools-phylo-paml=1.7.3=pl526_1
  - perl-bio-tools-run-alignment-clustalw=1.7.4=pl526_1
  - perl-bio-tools-run-alignment-tcoffee=1.7.4=pl526_2
  - perl-bioperl=1.7.2=pl526_11
  - perl-bioperl-core=1.007002=pl526_2
  - perl-bioperl-run=1.007002=pl526_4
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-cache-cache=1.08=pl526_0
  - perl-capture-tiny=0.48=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-cgi=4.44=pl526h14c3975_1
  - perl-class-data-inheritable=0.08=pl526_1
  - perl-class-inspector=1.34=pl526_0
  - perl-class-load=0.25=pl526_0
  - perl-class-load-xs=0.10=pl526h6bb024c_2
  - perl-class-method-modifiers=2.12=pl526_0
  - perl-clone=0.42=pl526h516909a_0
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-config-general=2.63=pl526_0
  - perl-constant=1.33=pl526_1
  - perl-convert-binary-c=0.78=pl526h6bb024c_3
  - perl-convert-binhex=1.125=pl526_1
  - perl-cpan-meta=2.150010=pl526_0
  - perl-cpan-meta-requirements=2.140=pl526_0
  - perl-cpan-meta-yaml=0.018=pl526_0
  - perl-crypt-rc4=2.02=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-data-optlist=0.110=pl526_2
  - perl-data-stag=0.14=pl526_1
  - perl-date-format=2.30=pl526_2
  - perl-db-file=1.852=pl526h14c3975_0
  - perl-dbd-sqlite=1.64=pl526h516909a_0
  - perl-dbi=1.642=pl526_0
  - perl-devel-globaldestruction=0.14=pl526_0
  - perl-devel-overloadinfo=0.005=pl526_0
  - perl-devel-stacktrace=2.04=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-digest-perl-md5=1.9=pl526_1
  - perl-digest-sha1=2.13=pl526h6bb024c_1
  - perl-dist-checkconflicts=0.11=pl526_2
  - perl-dynaloader=1.25=pl526_1
  - perl-email-date-format=1.005=pl526_2
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-error=0.17027=pl526_1
  - perl-eval-closure=0.14=pl526h6bb024c_4
  - perl-exception-class=1.44=pl526_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-cbuilder=0.280230=pl526_1
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-extutils-manifest=1.72=pl526_0
  - perl-extutils-parsexs=3.35=pl526_0
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-slurp-tiny=0.004=pl526_1
  - perl-file-sort=1.01=pl526_2
  - perl-file-temp=0.2304=pl526_2
  - perl-file-which=1.23=pl526_0
  - perl-findbin=1.51=pl526_2
  - perl-font-afm=1.20=pl526_2
  - perl-font-ttf=1.06=pl526_0
  - perl-gd=2.71=pl526he860b03_0
  - perl-getopt-long=2.50=pl526_1
  - perl-graph=0.9704=pl526_1
  - perl-graphics-colornames=2.11=pl526_0
  - perl-graphics-colorobject=0.5.0=pl526_1
  - perl-graphviz=2.24=pl526h734ff71_0
  - perl-html-element-extended=1.18=pl526_1
  - perl-html-entities-numbered=0.04=pl526_1
  - perl-html-formatter=2.16=pl526_0
  - perl-html-parser=3.72=pl526h6bb024c_5
  - perl-html-tableextract=2.13=pl526_2
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tidy=1.60=pl526_0
  - perl-html-tree=5.07=pl526_1
  - perl-html-treebuilder-xpath=0.14=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-image-info=1.38=pl526_1
  - perl-image-size=3.300=pl526_2
  - perl-io-html=1.001=pl526_2
  - perl-io-sessiondata=1.03=pl526_1
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-string=1.08=pl526_3
  - perl-io-stringy=2.111=pl526_1
  - perl-io-tty=1.12=pl526_1
  - perl-ipc-cmd=1.02=pl526_0
  - perl-ipc-run=20180523.0=pl526_0
  - perl-ipc-sharelite=0.17=pl526h6bb024c_1
  - perl-jcode=2.07=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-pp=4.04=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-lib=0.63=pl526_1
  - perl-libwww-perl=6.39=pl526_0
  - perl-libxml-perl=0.08=pl526_2
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-locale-maketext-simple=0.21=pl526_2
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-lwp-simple=6.15=pl526h470a237_4
  - perl-mailtools=2.21=pl526_0
  - perl-math-bezier=0.01=pl526_1
  - perl-math-cdf=0.1=pl526h14c3975_5
  - perl-math-derivative=1.01=pl526_0
  - perl-math-random=0.72=pl526h14c3975_2
  - perl-math-round=0.07=pl526_1
  - perl-math-spline=0.02=pl526_2
  - perl-math-vecstat=0.08=pl526_1
  - perl-memoize=1.03=pl526_2
  - perl-mime-base64=3.15=pl526_1
  - perl-mime-lite=3.030=pl526_1
  - perl-mime-tools=5.508=pl526_1
  - perl-mime-types=2.17=pl526_0
  - perl-mldbm=2.05=pl526_1
  - perl-module-build=0.4224=pl526_3
  - perl-module-corelist=5.20190524=pl526_0
  - perl-module-implementation=0.09=pl526_2
  - perl-module-load=0.32=pl526_1
  - perl-module-load-conditional=0.68=pl526_2
  - perl-module-loaded=0.08=pl526_0
  - perl-module-metadata=1.000036=pl526_0
  - perl-module-runtime=0.016=pl526_1
  - perl-module-runtime-conflicts=0.003=pl526_0
  - perl-moo=2.003004=pl526_0
  - perl-moose=2.2011=pl526hf484d3e_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-mro-compat=0.13=pl526_0
  - perl-net-http=6.19=pl526_0
  - perl-net-ssleay=1.88=pl526h90d6eec_0
  - perl-ntlm=1.09=pl526_4
  - perl-number-format=1.75=pl526_3
  - perl-ole-storage_lite=0.19=pl526_3
  - perl-package-deprecationmanager=0.17=pl526_0
  - perl-package-stash=0.38=pl526hf484d3e_1
  - perl-package-stash-xs=0.28=pl526hf484d3e_1
  - perl-params-check=0.38=pl526_1
  - perl-params-util=1.07=pl526h6bb024c_4
  - perl-params-validate=1.29=pl526h14c3975_1
  - perl-parent=0.236=pl526_1
  - perl-parse-recdescent=1.967015=pl526_0
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-pdf-api2=2.035=pl526_0
  - perl-perl-ostype=1.010=pl526_1
  - perl-pod-escapes=1.07=pl526_1
  - perl-pod-usage=1.69=pl526_1
  - perl-postscript=0.06=pl526_2
  - perl-readonly=2.05=pl526_0
  - perl-regexp-common=2017060201=pl526_0
  - perl-role-tiny=2.000008=pl526_0
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-set-intspan=1.19=pl526_1
  - perl-set-scalar=1.29=pl526_2
  - perl-soap-lite=1.19=pl526_1
  - perl-socket=2.027=pl526_1
  - perl-sort-naturally=1.03=pl526_2
  - perl-spreadsheet-parseexcel=0.65=pl526_2
  - perl-spreadsheet-writeexcel=2.40=pl526_2
  - perl-statistics-basic=1.6611=pl526_2
  - perl-statistics-descriptive=3.0702=pl526_0
  - perl-storable=3.15=pl526h14c3975_0
  - perl-sub-exporter=0.987=pl526_2
  - perl-sub-exporter-progressive=0.001013=pl526_0
  - perl-sub-identify=0.14=pl526h14c3975_0
  - perl-sub-install=0.928=pl526_2
  - perl-sub-name=0.21=pl526_1
  - perl-sub-quote=2.006003=pl526_1
  - perl-sub-uplevel=0.2800=pl526h14c3975_2
  - perl-svg=2.84=pl526_0
  - perl-svg-graph=0.02=pl526_3
  - perl-task-weaken=1.06=pl526_0
  - perl-template-toolkit=2.26=pl526_1
  - perl-test=1.26=pl526_1
  - perl-test-deep=1.128=pl526_1
  - perl-test-differences=0.67=pl526_0
  - perl-test-exception=0.43=pl526_2
  - perl-test-harness=3.42=pl526_0
  - perl-test-leaktrace=0.16=pl526h14c3975_2
  - perl-test-most=0.35=pl526_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-test-warn=0.36=pl526_1
  - perl-text-abbrev=1.02=pl526_0
  - perl-text-diff=1.45=pl526_0
  - perl-text-format=0.59=pl526_2
  - perl-text-parsewords=3.30=pl526_0
  - perl-tie-ixhash=1.23=pl526_2
  - perl-time-hires=1.9760=pl526h14c3975_1
  - perl-time-local=1.28=pl526_1
  - perl-timedate=2.30=pl526_1
  - perl-tree-dag_node=1.31=pl526_0
  - perl-try-tiny=0.30=pl526_1
  - perl-type-tiny=1.004004=pl526_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-unicode-map=0.112=pl526h6bb024c_3
  - perl-uri=1.76=pl526_0
  - perl-version=0.9924=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-dom=1.46=pl526_0
  - perl-xml-dom-xpath=0.14=pl526_1
  - perl-xml-filter-buffertext=1.01=pl526_2
  - perl-xml-libxml=2.0132=pl526h7ec2d77_1
  - perl-xml-libxslt=1.94=pl526_1
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44_01=pl526ha1d75be_1002
  - perl-xml-regexp=0.04=pl526_2
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-sax-writer=0.57=pl526_0
  - perl-xml-simple=2.25=pl526_1
  - perl-xml-twig=3.52=pl526_2
  - perl-xml-writer=0.625=pl526_2
  - perl-xml-xpath=1.44=pl526_0
  - perl-xml-xpathengine=0.14=pl526_2
  - perl-xsloader=0.24=pl526_0
  - perl-yaml=1.29=pl526_0
  - pip=20.1=pyh9f0ad1d_0
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h14c3975_1001
  - pybigwig=0.3.13=py27h5295baf_2
  - python=2.7.15=h5a48372_1011_cpython
  - python_abi=2.7=1_cp27mu
  - readline=8.0=hf8c457e_0
  - setuptools=44.0.0=py27_0
  - six=1.14.0=py_1
  - sqlite=3.30.1=hcee41ef_0
  - t_coffee=11.0.8=py27hea885bf_8
  - tar=1.29=h470a237_1
  - tidyp=1.04=1
  - tk=8.6.10=hed695b0_0
  - wheel=0.34.2=py_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
prefix: /usr/local/tools/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368
```

</details>

Since the .org one was failing with a CVMFS path, I re-created the config since it works on EU, and loaded up the .org cvmfs env to compare a bit.


<details>
<summary>Env Diff</summary>

```
(mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368) 15:22:20|[hxr@cosima:/tmp/circos.tkxmQjpe2Z]$ diff org-env.yml eu-env.yml
11c11
<   - ca-certificates=2020.4.5.2=hecda079_0
---
>   - ca-certificates=2020.4.5.1=hecc5488_0
20c20
<   - freetype=2.10.2=he06d7ca_0
---
>   - freetype=2.10.1=he06d7ca_0
25c25
<   - glib=2.64.3=h6f030ca_0
---
>   - glib=2.64.2=h6f030ca_0
31c31
<   - jpeg=9d=h516909a_0
---
>   - jpeg=9c=h14c3975_1001
33c33
<   - ld_impl_linux-64=2.34=h53a641e_5
---
>   - ld_impl_linux-64=2.34=h53a641e_0
38c38
<   - libedit=3.1.20191231=h46ee950_0
---
>   - libedit=3.1.20170329=hf8c457e_1001
42c42
<   - libgfortran-ng=7.5.0=hdf63c60_6
---
>   - libgfortran-ng=7.3.0=hdf63c60_5
47c47
<   - libssh2=1.9.0=hab1572f_2
---
>   - libssh2=1.8.2=h22169c7_2
57c57
<   - lz4-c=1.9.2=he1b5a44_1
---
>   - lz4-c=1.9.2=he1b5a44_0
303c303
<   - pip=20.1.1=pyh9f0ad1d_0
---
>   - pip=20.1=pyh9f0ad1d_0
311c311
<   - six=1.15.0=pyh9f0ad1d_0
---
>   - six=1.14.0=py_1
334,335c334
< prefix: /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368
<
---
> prefix: /usr/local/tools/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368
```

</details>

 but that doesn't look too bad i guess. Running it works fine though. So, maybe there's something wrong with the configuration files that are passed to circos. @cat-bro any chance you can get me a copy of the failed working dir?

```
(mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368) 15:25:03|[hxr@cosima:/tmp/circos.tkxmQjpe2Z]$ circos -conf circos/conf/circos.conf
debuggroup summary 5.73s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002
debuggroup summary 5.73s current working directory /tmp/circos.tkxmQjpe2Z
debuggroup summary 5.73s command /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/circos -conf circos/conf/circos.conf
debuggroup summary 5.73s loading configuration from file circos/conf/circos.conf
debuggroup summary 5.73s found conf file circos/conf/circos.conf
debuggroup summary 5.82s debug will appear for these features: output,summary
debuggroup summary 5.82s bitmap output image ./circos.png
debuggroup summary 5.82s SVG output image ./circos.svg
debuggroup summary 5.82s parsing karyotype and organizing ideograms
debuggroup summary 5.82s karyotype has 2 chromosomes of total size 56,082
debuggroup summary 5.82s applying global and local scaling
debuggroup summary 5.82s allocating image, colors and brushes
debuggroup summary 10.52s drawing 2 ideograms of total size 56,082
debuggroup summary 10.52s drawing highlights and ideograms
debuggroup output 10.53s generating output
debuggroup output 10.81s created PNG image ./circos.png (40 kb)
debuggroup output 10.81s created SVG image ./circos.svg (2 kb)
```

**Comment by cat-bro** [comment] 2021-05-31 00:15
@hexylena I'll email the failed working dir

**Comment by hexylena** [comment] 2022-11-24 14:13
Should be fixed in newer versions of circos

**Closed by hexylena** 2022-11-24 14:13 UTC
