### ISSUE TITLE
msi-analyte-distribution: total number of "Number of m/z features"

### ISSUE THREAD

**Issue by hrhotz** [galaxyproject/training-material#2173] opened 2020-12-01 16:12 UTC
When I am running the tutorial withe the provided example data, I get a total number of "Number of m/z features" of 19851 and not as written in the tutorial: 9927

Also, I do get much higher intensities in the spectra plots

I have the same issues locally on my own server and when running the tutorial on usegalaxy.eu

Regards, Hans-Rudolf

**Comment by hrhotz** [comment] 2020-12-01 16:13
ping @foellmelanie

**Comment by foellmelanie** [comment] 2020-12-01 20:51
Hi Hans-Rudolf, 

the problems might arise from using old tool versions. MSI filtering version 2.6.0.0. should give ~9900 mz features. For this training I already included the tool versions, so you could run it from inside the European Galaxy server to ensure that you use the right tool in the right version. If this doesn't help just send me your history for inspection ;) 

Thanks,
Melanie

**Comment by hrhotz** [comment] 2020-12-02 06:59
Hi Melanie

I have already tried Galaxy version 2.6.0.1 (history item 2) and version 2.6.0.0 (history item 4), each time I get 19851
https://usegalaxy.eu/u/87d25cda700e42fa917c60bb142e8c3a/h/test-cardinal-tools-20201201
(you can ignore (history item 5)

Hans-Rudolf

**Comment by foellmelanie** [comment] 2020-12-02 09:08
Hi Hans-Rudolf, 

thanks a lot for sharing the history, that was very helpful. The problem is that the calculation of the binning size for the processed files has changed from half window size to full window size. The results should fit when replacing 0.1 mz with 0.2 mz in all steps:

Processed imzML file”: yes
    “Mass accuracy to which the m/z values will be binned”: 0.2
    “Unit of the mass accuracy”: mz

Sorry that the GTN is not up to date with the current tool versions, I will try my best to update both MSI metabolomics trainings according to the current tools as soon as possible.

Cheers,
Melanie

**Comment by hrhotz** [comment] 2020-12-02 09:47
great - thanks!
I will try again later

**Comment by hrhotz** [comment] 2020-12-03 14:12
Hi Melanie

I am sorry to be a pain in the neck....I have re-run the analysis with "0.2 mz" (see: https://usegalaxy.eu/u/87d25cda700e42fa917c60bb142e8c3a/h/test-cardinal-tools-20201203-using-02 )

History items 2 (MSI Qualitycontrol) and 3 (MSI plot spectra) reflect the tutorial much closer.

Unfortunately, the spectra of different chilli compartments (history item 5) is still completely off. To me, it looks like, as I if I am using the wrong coordinates in the annotation file - any idea of what I am actually doing wrong? 

Hans-Rudolf

**Comment by foellmelanie** [comment] 2021-01-21 13:51
Hi Hans-Rudolf, 

happy new year and sorry for the super late reply! 

It was probably a problem with the spectra plot tool version, which should be fixed in the new version 2.6.0.3. It might still look a bit different than in the training material, which needs a few updates. Sorry about that!

Cheers,
Melanie

**Comment by hrhotz** [comment] 2021-01-21 14:11
no worries, I'll wait for the updates to the tutorial

**Comment by bebatut** [comment] 2021-10-12 11:38
@hrhotz @foellmelanie has this issue been solved with #2454?

**Comment by hrhotz** [comment] 2021-10-19 15:27
Will try to find some time this week to check.....sorry for the delays

**Closed** 2021-10-21 10:33 UTC
Labels: topic:metabolomics
