### ISSUE TITLE
add links from Galaxy tools to GTN

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#3081] opened 2021-11-29 08:56 UTC
Now that we have EDAM ontologies in Galaxy and the GTN has an API I'm wondering if we can link from tools back to trainings.

This is a normal tool form:

![grafik](https://user-images.githubusercontent.com/469983/143836907-bb943b2a-e322-47d7-a437-7c59f01d0554.png)

A few ideas:

* below at the citation box, have a training box
* this training box could list all training this tool was used (not limited to the specific tool version)
* additionally we could use the EDAM topic to give trainings for the same "topic"
* having a lecture-hat at the top bar of the tool that jumps to the training box to make it more visible

**Comment by hexylena** [comment] 2021-11-29 09:02
duplicate of https://github.com/galaxyproject/training-material/issues/3064 ;) 

I was thinking to improve the hat webhook to be a bit more fancy and maybe support knowing 'which tool are you currently looking at' and have a shortcut for showing which trainings cover that (it will need some more work on the GTN side.) but this could also be in a box below the tool, it would be interesting.

**Comment by bgruening** [comment] 2021-11-29 09:10
Missed that, but I don't think it's a pure duplicate. I think it has some merits to improve this into the tool form. The help section fits nicely imho and can give us a lot of space for content even without the webhook enabled.

**Comment by hexylena** [comment] 2021-11-29 09:12
No, not a pure duplicate, but same concept eh? Definitely has merits! Let's do it.

I like the help section but I never read them on other tools :eyes: Especially for tools with really long help (e.g. jbrowse) I never bother scrolling down far enough to see it. But this is one of those things where everyone and every tool is different so maybe we can put the same content in multiple places was more how I was thinking.

**Comment by hexylena** [comment] 2023-02-17 10:48
> below at the citation box, have a training box
> this training box could list all training this tool was used (not limited to the specific tool version)

Yes, I think this is now ready/possible with https://training.galaxyproject.org/training-material/by-tool/devteam/fastqc.html. Can be exposed as a JSON API as well if that's better.

**Comment by hexylena** [comment] 2023-06-30 09:34
This is so cool! Love it

![image](https://github.com/galaxyproject/training-material/assets/458683/4e5237d9-51fb-4856-b13e-273d85b88001)

**Closed by hexylena** 2023-06-30 09:34 UTC
