### ISSUE TITLE
Search FAQs gives same FAQ several times

### ISSUE THREAD

**Issue by beatrizserrano** [galaxyproject/training-material#3411] opened 2022-04-17 13:14 UTC
![image](https://user-images.githubusercontent.com/11300231/163715832-39df0585-f312-47a5-8eff-b27d58ec5040.png)

**Comment by jennaj** [comment] 2022-04-22 05:26
Noticed the tutorials are not sorting as before, too.

Try searching "collections" or "workflows" -- the most relevant tutorials are not at the top anymore. 

Guessing the search params changed. Noticed it today, may have started 2-3 days ago (was working earlier than then).

**Comment by hexylena** [comment] 2022-05-12 10:44
@jennaj which tutorials are most relevant for those topics? `workflows` looks fine to me, collections too.

I cannot reproduce @beatrizserrano's screenshot, so, closing. This works fine as far as I can tell

**Comment by hexylena** [comment] 2022-05-12 10:45
ok, I see the issue. The difference between

https://training.galaxyproject.org/training-material/search?query=igv
and going to the search page and entering `igv` is stark.

**Comment by hexylena** [comment] 2022-05-12 10:46
The duplicates are because @shiltemann duplicated the IGV faq around to each of the relevant tutorials, I didn't consider we'd have identical FAQ files.

But easy to exclude via ignoring symlinks

**Closed** 2022-05-12 12:10 UTC
