### ISSUE TITLE
GTN curated tutorial feedback/add link icon to tutorial sub-topics

### ISSUE THREAD

**Issue by otatadeabigail** [galaxyproject/training-material#3043] opened 2021-11-15 23:55 UTC
While looking through the tutorial feedbacks from the link below to see which issues haven't been attended to
https://training.galaxyproject.org/training-material/feedback.html
I noticed that when the sub-topics are clicked it only shows the tutorial feedbacks from that particular topic, there isn't a link that can take me directly to the site of the tutorial. I first, need to go back to the main topic like the picture below and then navigate through the sub- topic that has the feedback I want to check
![Screenshot_20211116-002244~3](https://user-images.githubusercontent.com/78880128/141869547-32b11380-23ca-44e8-800c-cffa427d7619.png)
This is a bit of a challenge because this particular topic in the screenshot above has at least 18 subtopics. Which means after reading the feedback from one of the 18 sub-topics, to access it's link, I first need to scroll back up, click on the main topic(Galaxy server administration), then find the sub-topic, usually by then, i'd have forgotten the title, then i have to go back to check again.
Suggestion: Add a link Icon like the one in this screenshot below 
![Screenshot_20211116-002244~3](https://user-images.githubusercontent.com/78880128/141869936-6385dc96-60f3-430a-8b82-12daa7f1def2.png)
Add a link icon beside all the sub-topics, so that when the icon is clicked, it leads straight to the tutorial. But when the sub-topic itself is clicked, it shows the drop-down of the tutorial feedback. I believe it will be great for optimized user experience and makes it easier and faster for us to look through the tutorial feedback and the tutorial itself, to see which is still viable and needs to be raised as an issue on GitHub.
![Screenshot_20211116-002441~2](https://user-images.githubusercontent.com/78880128/141870440-5f3b9e8e-44c4-455e-890d-0b2a9f89a153.png)

**Comment by hexylena** [comment] 2021-11-16 10:31
This is a duplicate of https://github.com/galaxyproject/training-material/issues/2987 so we will be closing it in order to not need to track duplicate issues. Thank you for the detailed issue report though!

**Closed by hexylena** 2021-11-16 10:31 UTC

**Comment by otatadeabigail** [comment] 2021-11-16 19:25
oh, I didn't realize. My bad!

**Comment by hexylena** [comment] 2021-11-17 06:34
No problem at all! :)
